export const MOODS = [
  { id: 'happy', label: 'Happy', emoji: '😀', color: 'text-amber-500 bg-amber-50 dark:bg-amber-950/40 border-amber-200 dark:border-amber-800' },
  { id: 'excited', label: 'Excited', emoji: '🥳', color: 'text-pink-500 bg-pink-50 dark:bg-pink-950/40 border-pink-200 dark:border-pink-800' },
  { id: 'calm', label: 'Calm', emoji: '😌', color: 'text-emerald-500 bg-emerald-50 dark:bg-emerald-950/40 border-emerald-200 dark:border-emerald-800' },
  { id: 'neutral', label: 'Neutral', emoji: '😐', color: 'text-slate-500 bg-slate-50 dark:bg-slate-900/40 border-slate-200 dark:border-slate-800' },
  { id: 'sad', label: 'Sad', emoji: '😔', color: 'text-blue-500 bg-blue-50 dark:bg-blue-950/40 border-blue-200 dark:border-blue-800' },
  { id: 'angry', label: 'Angry', emoji: '😡', color: 'text-rose-500 bg-rose-50 dark:bg-rose-950/40 border-rose-200 dark:border-rose-800' },
  { id: 'stressed', label: 'Stressed', emoji: '😰', color: 'text-orange-500 bg-orange-50 dark:bg-orange-950/40 border-orange-200 dark:border-orange-800' },
  { id: 'tired', label: 'Tired', emoji: '😴', color: 'text-indigo-500 bg-indigo-50 dark:bg-indigo-950/40 border-indigo-200 dark:border-indigo-800' },
  { id: 'anxious', label: 'Anxious', emoji: '😟', color: 'text-purple-500 bg-purple-50 dark:bg-purple-950/40 border-purple-200 dark:border-purple-800' },
];

export const TEMPLATES = [
  {
    id: 'classic',
    name: 'Classic Journal',
    icon: 'BookOpen',
    description: 'Traditional diary style with a distraction-free paper writing feel.',
    tagline: 'Your everyday sanctuary for thoughts and moments',
    accentColor: 'from-amber-500 to-orange-500',
    badgeColor: 'bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300',
  },
  {
    id: 'reflection',
    name: 'Daily Reflection',
    icon: 'Sparkles',
    description: 'Structured sections for highlights, challenges, gratitude, and lessons.',
    tagline: 'Reflect deeply on what shaped your day',
    accentColor: 'from-indigo-500 to-purple-500',
    badgeColor: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950/50 dark:text-indigo-300',
  },
  {
    id: 'planner',
    name: 'Daily Planner',
    icon: 'CheckSquare',
    description: 'Goals, interactive checklists, completed tasks, and tomorrow priorities.',
    tagline: 'Structure your day and conquer priorities',
    accentColor: 'from-blue-500 to-cyan-500',
    badgeColor: 'bg-blue-100 text-blue-800 dark:bg-blue-950/50 dark:text-blue-300',
  },
  {
    id: 'mood',
    name: 'Mood Journal',
    icon: 'Heart',
    description: 'Visual mood selector, 1-10 intensity score, and emotional check-in.',
    tagline: 'Check in with your feelings and mental wellbeing',
    accentColor: 'from-rose-500 to-pink-500',
    badgeColor: 'bg-rose-100 text-rose-800 dark:bg-rose-950/50 dark:text-rose-300',
  },
  {
    id: 'gratitude',
    name: 'Gratitude Journal',
    icon: 'Sun',
    description: 'Dynamic gratitude list, moments of joy, appreciation, and optimism.',
    tagline: 'Count your blessings and cultivate joy',
    accentColor: 'from-yellow-500 to-amber-500',
    badgeColor: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-950/50 dark:text-yellow-300',
  },
  {
    id: 'free_writing',
    name: 'Free Writing',
    icon: 'Feather',
    description: 'Expansive distraction-free blank canvas for uninterrupted flow.',
    tagline: 'Unleash your unfiltered stream of consciousness',
    accentColor: 'from-teal-500 to-emerald-500',
    badgeColor: 'bg-teal-100 text-teal-800 dark:bg-teal-950/50 dark:text-teal-300',
  },
  {
    id: 'travel',
    name: 'Travel Journal',
    icon: 'Compass',
    description: 'Document destinations, food, highlights, companions, and photo gallery.',
    tagline: 'Capture adventures, places, and memories',
    accentColor: 'from-cyan-500 to-blue-500',
    badgeColor: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-950/50 dark:text-cyan-300',
  },
  {
    id: 'study',
    name: 'Study Journal',
    icon: 'GraduationCap',
    description: 'Notebook-inspired layout for subjects, duration, takeaways, and questions.',
    tagline: 'Accelerate learning and solidify insights',
    accentColor: 'from-violet-500 to-indigo-500',
    badgeColor: 'bg-violet-100 text-violet-800 dark:bg-violet-950/50 dark:text-violet-300',
  },
  {
    id: 'work',
    name: 'Work Journal',
    icon: 'Briefcase',
    description: 'Professional structured log for achievements, tasks, meetings, and solutions.',
    tagline: 'Track workplace accomplishments and resolve blockers',
    accentColor: 'from-slate-600 to-slate-800',
    badgeColor: 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300',
  },
  {
    id: 'dream',
    name: 'Dream Journal',
    icon: 'Moon',
    description: 'Creative dreamy layout with nocturnal aesthetics, emotions, and interpretations.',
    tagline: 'Record subconscious journeys and night visions',
    accentColor: 'from-purple-500 to-fuchsia-600',
    badgeColor: 'bg-purple-100 text-purple-800 dark:bg-purple-950/50 dark:text-purple-300',
  },
];

export const getMoodById = (id) => MOODS.find((m) => m.id === id);
export const getTemplateById = (id) => TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];

